# Generated by Django 3.0.5 on 2021-04-28 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='project',
            name='description_candidate',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(default=False, max_length=140),
        ),
        migrations.AddField(
            model_name='project',
            name='timeline',
            field=models.CharField(default='[]', max_length=2048),
        ),
    ]
