# Generated by Django 3.0.5 on 2021-04-29 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20210428_0429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(default='En desarrollo', max_length=140),
        ),
    ]
